services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: rum
      POSTGRES_USER: rum
      POSTGRES_PASSWORD: Rum1234
    ports:
      - "2345:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rum -d rum"]
      interval: 10s
      timeout: 5s
      retries: 5
