apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scrum-master-ai.fullname" . }}
  labels:
    {{- include "scrum-master-ai.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "scrum-master-ai.databaseUrl" . | b64enc | quote }}
